### ISSUE TITLE
It can not be downloaded if the asset is not an archive file.

### ISSUE THREAD

**Issue by sawanoboly** [Songmu/ghg#7]
Such as ctop, https://github.com/bcicen/ctop/releases/tag/v0.4.1 .

It returns asset names as below

- `ctop-0.4.1-darwin-amd64`
- `ctop-0.4.1-linux-amd64`
- `ctop-0.4.1-linux-arm`

So, `ghg get` will be `no assets available`.

**Comment by Songmu** [comment]
I see. The ctop executable file is uploaded as it is without being compressed. I will consider how to handle it.

**Comment by Songmu** [comment]
Resolved at #8 and released v0.1.0. Thanks!
